// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACFOB_AVrsBHfF9GIObn3_l7CdxdQvdCo',
    appId: '1:703069721052:android:aeea2ed220d00f9ad13f19',
    messagingSenderId: '703069721052',
    projectId: 'messapp-bcb17',
    storageBucket: 'messapp-bcb17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC20iVfOtosbhzrgJInLhX0RCm7xF0bWnQ',
    appId: '1:703069721052:ios:fe29b1176aa521d4d13f19',
    messagingSenderId: '703069721052',
    projectId: 'messapp-bcb17',
    storageBucket: 'messapp-bcb17.appspot.com',
    androidClientId: '703069721052-kvub8hejuukm38ji2h79ulb4dvc3el06.apps.googleusercontent.com',
    iosClientId: '703069721052-pescf8ijrf4f73bciovdip93lo2tdp1s.apps.googleusercontent.com',
    iosBundleId: 'com.teamfleg.messapp',
  );
}
